=== mnaskret/CoalescenceMN/CoalescerMN.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:shine="http://cern.ch/na61/schema/types">

  <xs:import
    namespace="http://cern.ch/na61/schema/types"
    schemaLocation="[SCHEMAPATH_IMPORTS]/ShineSchemaTypes.xsd"/>

  <xs:import
    namespace="http://cern.ch/na61/schema/types"
    schemaLocation="[SCHEMAPATH_SRCDIR]/Utilities/Reader/ShineSchemaTypes.xsd"/>

  <xs:element name="CoalescerMN">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="p0" type="xs:double"/>
        <xs:element name="antiP0" type="xs:double"/>
        <xs:element name="beamMomentum" type="xs:double"/>
        <xs:element name="targetAtomicNumber" type="xs:int"/>
        <xs:element name="targetMassNumber" type="xs:int"/>
        <xs:element name="beamAtomicNumber" type="xs:int"/>
        <xs:element name="beamMassNumber" type="xs:int"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== mnaskret/CoalescenceMN/CoalescerMN.xml
<?xml version="1.0" encoding="iso-8859-1"?>

<!-- Configuration of Module CoalescerMN -->

<CoalescerMN     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation='[SCHEMAPATH]/CoalescerMN.xsd'>


  <antiP0> 4.89 </antiP0> <!-- MeV antideuterons -->
  <p0> 493.31 </p0> <!-- MeV deuterons -->
  <beamMomentum> 31 </beamMomentum> <!-- GeV -->
  <!-- Carbon target -->
  <targetAtomicNumber> 31 </targetAtomicNumber> <!-- int -->
  <targetMassNumber> 31 </targetMassNumber> <!-- int -->
  <!-- p beam -->
  <beamAtomicNumber> 1 </beamAtomicNumber> <!-- int -->
  <beamMassNumber> 1 </beamMassNumber> <!-- int -->

</CoalescerMN>
